# Word2Vec

In [129]:
import gensim
from gensim.models import KeyedVectors
import numpy as np
import tensorflow as tf

In [ ]:
import gensim
from gensim.models import KeyedVectors

path = 'D:/DEpression_project/GoogleNews-vectors-negative300.bin'
# Load Google's pre-trained Word2Vec model.
model = KeyedVectors.load_word2vec_format(path, binary=True)

In [42]:
len(model.vocab)

3000000

In [53]:
for k,v in model.vocab.items():
    if k == 'depressed':
        print (v)

Vocab(count:2990524, index:9476)


In [62]:
print (type(model.syn0))
print (model.syn0.shape)
print (len(model.wv.index2word))

<class 'numpy.ndarray'>
(3000000, 300)


C:\Users\Bao\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  if __name__ == '__main__':
C:\Users\Bao\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  from ipykernel import kernelapp as app
C:\Users\Bao\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  app.launch_new_instance()


AttributeError: 'list' object has no attribute 'shape'

In [65]:
model.wv.syn0[9476]

C:\Users\Bao\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  if __name__ == '__main__':
C:\Users\Bao\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  if __name__ == '__main__':


array([ 0.06298828,  0.09716797, -0.3203125 ,  0.10742188, -0.19140625,
        0.23730469, -0.06494141,  0.08007812,  0.390625  ,  0.04272461,
       -0.00311279, -0.01818848, -0.05273438, -0.0025177 ,  0.04077148,
       -0.06347656, -0.13476562,  0.23046875,  0.23339844, -0.19140625,
        0.03295898, -0.06347656,  0.03930664, -0.01843262,  0.05053711,
        0.0057373 , -0.03466797,  0.06933594,  0.12207031, -0.01403809,
        0.10400391,  0.00093079, -0.04370117, -0.10107422,  0.00488281,
        0.08691406, -0.15625   , -0.11767578, -0.16601562,  0.09521484,
        0.1875    ,  0.05004883,  0.17871094, -0.10498047,  0.01623535,
       -0.07421875, -0.11279297,  0.05029297, -0.0480957 , -0.02026367,
       -0.12060547, -0.0324707 , -0.40625   ,  0.28125   ,  0.07324219,
       -0.19238281, -0.11767578,  0.08496094, -0.02087402, -0.07080078,
       -0.00390625,  0.14550781, -0.2734375 ,  0.07128906,  0.02563477,
        0.05664062,  0.04882812, -0.05249023,  0.01403809, -0.18

In [73]:
#zip the two lists containing vectors and words
embd_mat = zip(model.index2word, model.syn0)

C:\Users\Bao\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  from ipykernel import kernelapp as app


The word vectors are stored in a KeyedVectors instance in model.wv. This separates the read-only word vector lookup operations in KeyedVectors from the training code in Word2Vec:

In [44]:
model.wv['depressed']

C:\Users\Bao\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  if __name__ == '__main__':


array([ 0.06298828,  0.09716797, -0.3203125 ,  0.10742188, -0.19140625,
        0.23730469, -0.06494141,  0.08007812,  0.390625  ,  0.04272461,
       -0.00311279, -0.01818848, -0.05273438, -0.0025177 ,  0.04077148,
       -0.06347656, -0.13476562,  0.23046875,  0.23339844, -0.19140625,
        0.03295898, -0.06347656,  0.03930664, -0.01843262,  0.05053711,
        0.0057373 , -0.03466797,  0.06933594,  0.12207031, -0.01403809,
        0.10400391,  0.00093079, -0.04370117, -0.10107422,  0.00488281,
        0.08691406, -0.15625   , -0.11767578, -0.16601562,  0.09521484,
        0.1875    ,  0.05004883,  0.17871094, -0.10498047,  0.01623535,
       -0.07421875, -0.11279297,  0.05029297, -0.0480957 , -0.02026367,
       -0.12060547, -0.0324707 , -0.40625   ,  0.28125   ,  0.07324219,
       -0.19238281, -0.11767578,  0.08496094, -0.02087402, -0.07080078,
       -0.00390625,  0.14550781, -0.2734375 ,  0.07128906,  0.02563477,
        0.05664062,  0.04882812, -0.05249023,  0.01403809, -0.18

In [16]:
model.wv.similarity('depression', 'bipolar')

C:\Users\Bao\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  if __name__ == '__main__':


0.5463774512425825

# Loading pre-trained word embeddings

In [86]:
path = 'D:/DEpression_project/GoogleNews-vectors-negative300.bin'
# Load Google's pre-trained Word2Vec model.
model = KeyedVectors.load_word2vec_format(path, binary=True)

embd = model.syn0   # embd is numpy array
embd_dim = embd.shape[1]   # should be 300
vocab = model.vocab.keys()
vocab_size = len(vocab)

print ('The embeddings dimension is '+ str(embd_dim))
print ('The vocabulary size is '+ str(vocab_size))

The embeddings dimension is 300
The vocabulary size is 3000000


C:\Users\Bao\Anaconda3\lib\site-packages\ipykernel\__main__.py:5: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).


# Embedding Layer

After loading in the vectors, we need to use them to initialize W of the embedding layer in your network.

In [88]:
W = tf.Variable(tf.constant(0.0, shape=[vocab_size, embd_dim]),
                trainable=False, name="W")
embd_placeholder = tf.placeholder(tf.float32, [vocab_size, embd_dim])
embd_init = W.assign(embd_placeholder)

After creating a session and initialize global variables, run the embedding_init operation by feeding in the 2-D array embedding.

In [89]:
sess.run(embd_init, feed_dict={embd_placeholder: embd})

array([[ 1.1291504e-03, -8.9645386e-04,  3.1852722e-04, ...,
        -1.5640259e-03, -1.2302399e-04, -8.6307526e-05],
       [ 7.0312500e-02,  8.6914062e-02,  8.7890625e-02, ...,
        -4.7607422e-02,  1.4465332e-02, -6.2500000e-02],
       [-1.1779785e-02, -4.7363281e-02,  4.4677734e-02, ...,
         7.1289062e-02, -3.4912109e-02,  2.4169922e-02],
       ...,
       [-1.9653320e-02, -9.0820312e-02, -1.9409180e-02, ...,
        -1.6357422e-02, -1.3427734e-02,  4.6630859e-02],
       [ 3.2714844e-02, -3.2226562e-02,  3.6132812e-02, ...,
        -8.8500977e-03,  2.6977539e-02,  1.9042969e-02],
       [ 4.5166016e-02, -4.5166016e-02, -3.9367676e-03, ...,
         7.9589844e-02,  7.2265625e-02,  1.3000488e-02]], dtype=float32)

# Vocabulary

Suppose you have raw documents, the first thing you need to do is to build a vocabulary, which will map each word into an id. So we would choose the pre-trained model when we build the vocabulary: word-id maps.

In [141]:
#prepocess our own data
import nltk 
from nltk.tokenize import word_tokenize
import numpy as np
import random
import pickle
from collections import Counter

hm_lines = 10000000

def create_lexicon(pos, neg):
    lexicon = []
    for fi in [pos, neg]:
        with open(fi, 'r') as f:
            contents = f.readlines()
            for line in contents[:hm_lines]:
                all_words = word_tokenize(line.lower())
                lexicon += list(all_words)
                
    w_counts = Counter(lexicon)
    
    lexicon2 = []
    for w in w_counts:
        if 1000 > w_counts[w] > 50:
            lexicon2.append(w)
        
    return lexicon2    

def sample_handling(sample, lexicon, label):
    featureset = []
    
    with open(sample, 'r') as f:
        contents = f.readlines()
        for line in contents[:hm_lines]:
            current_words = word_tokenize(line.lower())
            features = np.zeros(len(lexicon))
            for word in current_words:
                if word.lower() in lexicon:
                    index_value = lexicon.index(word.lower())
                    features[index_value] += 1.0
            features = list(features)
            featureset.append([features, label])
            
    return featureset

def creat_featuresets_and_labels(pos, neg, test_size=0.2):
    lexicon = create_lexicon(pos, neg)
    features = []
    features += sample_handling('pos.txt', lexicon, [1,0])
    features += sample_handling('neg.txt', lexicon, [0,1])
    random.shuffle(features)
    
    features = np.array(features)
    
    testing_size = int(test_size*len(features))
    
    train_x = list(features[:, 0][:-testing_size])
    train_y = list(features[:, 1][:-testing_size])
    
    test_x = list(features[:, 0][-testing_size:])
    test_y = list(features[:, 1][-testing_size:])
    
    return train_x, train_y, test_x, test_y
    
if __name__ == '__main__':
    train_x, train_y, test_x, test_y = creat_featuresets_and_labels('pos.txt', 'neg.txt')
    with open('sentiment_set.pickle', 'wb') as f:
        pickle.dump([train_x, train_y, test_x, test_y], f)

In [132]:
#from create_sentiment_featuresets import creat_featuresets_and_labels
#train_x, train_y, test_x, test_y = creat_featuresets_and_labels('pos.txt', 'neg.txt')

NameError: name 'np' is not defined

In [142]:
pickle_off = open("sentiment_set.pickle","rb")
train_x, train_y, test_x, test_y = pickle.load(pickle_off)

In [137]:
doc_length = []
for i in train_x:
    doc_length.append(len(i))
max_doc_length = max(doc_length)
print (max_doc_length)

407


In [144]:
input_x = tf.placeholder(tf.int32, [None, len(train_x[0])], name="input_x")
#input_y = tf.placeholder(tf.float32, [None, num_classes = 2)], name="input_y")

In [145]:
embd_chars = tf.nn.embedding_lookup(W, input_x)

In [ ]:
# reshape input data
x_unstack = tf.unstack(embedded_chars, len(train_x[0]), 1)

In [139]:
from tensorflow.contrib import learn
#init vocab processor
vocab_processor = learn.preprocessing.VocabularyProcessor(max_doc_length)
#fit the vocab from glove
pretrain = vocab_processor.fit(vocab)
#transform inputs
x = np.array(list(vocab_processor.transform(input_x)))

TypeError: Tensor objects are not iterable when eager execution is not enabled. To iterate over this tensor use tf.map_fn.

# FastText 

In [33]:
from gensim.models import KeyedVectors

# Creating the model
path = 'D:/Depression_project/wiki-news-300d-1M.vec'
model2 = KeyedVectors.load_word2vec_format(path)

use this link to see how to install tensorflow on Windows:
https://www.tensorflow.org/install/install_windows

If you want to use tenserflow in Jupyer Notebook, use the following:

In [29]:
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))

b'Hello, TensorFlow!'


# Placeholders for input, output

In [ ]:
input_x = tf.placeholder(tf.float32, [None, doc_length], name="input_x")
input_y = tf.placeholder(tf.int32, [None, num_classes], name="input_y")

# Use pre-trained embedding matrix

In [ ]:
embed_mat = 